# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[(b'F', b'Feeling'), (b'W', b'Working'), (b'E', b'Entertainment')], max_length=50),
        ),
    ]
