# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20160307_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artiist',
            new_name='artist',
        ),
    ]
